server:
  port: 100018
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-coupon
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://172.16.68.110:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848





mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.nanjing.**.entity
  # 配置mapper的扫描，找到所有的.xml映射文件
  mapper-locations: classpath:/mapper/**/*.xml

  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0

#默认Feign客户端只等待1s，如果我们的业务处理超过1s，Feign客户端就会直接返回并且报错。
#为了避免这种情况，我们需要设置Feign客户端超时控制。但是Feign的超时时长是通过Ribbon控制的。
#所以我们需要配置Ribbon的超时时长配置了
ribbon:
  #建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 2000
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 2000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.nanjing.gulimall.coupon.feign.CouponFeignClient: debug

